# Tạo file "secret.yaml" rồi thực hiện điền vào các placeholder
# Chú ý encoding base64 key trước
# Lấy key base64: powershell -Command "do { $inputString = Read-Host 'Nhập chuỗi'; if ($inputString -eq 'exit') { break }; $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($inputString)); Write-Output \"Base64: $encoded`n\" } while ($true)"

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  jwt_key: <BASE64_ENCODED_SECRET>
