apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 5053
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: post-srv
                port:
                  number: 5050
          - path: /posts/(.*)/comments/create
            pathType: ImplementationSpecific
            backend:
              service:
                name: comment-srv
                port:
                  number: 5051
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
