# Gọi thư viện tạo khối container
FROM node:20-alpine

#Sửa lỗi kết nối Kubernetes
ENV CI=true
ENV WDS_SOCKET_PORT=0

#Chỉ định folder sẽ dùng cho những câu lệnh tiếp theo (mục đích là để tránh trùng folder)
WORKDIR /usr/app

# Thực hiện câu lệnh này để nếu như có đổi file bên ngoài mà không liên quan tới thư viện thì không cần cập nhật thư viện
COPY ./package.json ./

# Câu lệnh cập nhật thư viện
RUN npm install

# Copy toàn bộ các file
COPY ./ ./

# Default command - Câu lệnh chạy chương trình. Khong dung nodemon vi day khong phai moi truong dev.
CMD ["node", "./app.js"]