apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/auth.yaml
    - ./infra/k8s/ingress.yaml
    - ./infra/k8s/mongo-create.yaml
    - ./infra/k8s/secret.yaml
build:
  local:
    push: false
  artifacts:
    - image: ticket_project/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
